---

base_path: .
base_url: https://api.crowdin.com
preserve_hierarchy: 1
files:
  - source: /CrowdinLocalizationDemo/en.lproj/*.strings
    translation: /CrowdinLocalizationDemo/%osx_code%/%original_file_name%
