"base_path": "."
"base_url": "https://api.crowdin.com"

"preserve_hierarchy": true
"files": [
  {
    "source": "/CrowdinLocalizationDemo/en.lproj/*.strings",
    "translation": "/CrowdinLocalizationDemo/%osx_code%/%original_file_name%"
  },
]